# Generated by Django 3.2.13 on 2022-05-18 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='apresent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='bairro',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='cidade',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='Nº CPF'),
        ),
        migrations.AddField(
            model_name='user',
            name='cro',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='Nº CRO'),
        ),
        migrations.AddField(
            model_name='user',
            name='endereco',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='especialidade',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='estado',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='upload', verbose_name='Logo'),
        ),
        migrations.AddField(
            model_name='user',
            name='nrTelCelular',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Nº telefone celular'),
        ),
        migrations.AddField(
            model_name='user',
            name='texto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='upload', verbose_name='Receituario'),
        ),
    ]
