# Generated by Django 3.2.13 on 2022-05-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220518_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sobrenome',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
