# Generated by Django 3.2.13 on 2022-05-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_sobrenome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='apresent',
            new_name='apresentacao',
        ),
        migrations.AddField(
            model_name='user',
            name='clinica',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='especialidade',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome da Clinica'),
        ),
    ]
