# Generated by Django 3.2.13 on 2022-05-18 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20220518_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='clinica',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome da Clinica'),
        ),
        migrations.AlterField(
            model_name='user',
            name='especialidade',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
